version: "3.7"
services:
  app:
    build:
      args:
        user: stefan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: takeaway-mailer
    container_name: takeaway-mailer-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tkwmailer
  db:
    image: mysql:5.7
    container_name: tkwmailer-db
    restart: unless-stopped
    ports:
      - 3356:3306
    environment:
      MYSQL_DATABASE: tkwmailer
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: tkwmailer
      MYSQL_USER: tkwmailer_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - tkwmailer
  redis:
    image: redis:alpine
    container_name: tkwmailer-redis
    restart: unless-stopped
    networks:
      - tkwmailer
  nginx:
    image: nginx:1.17-alpine
    container_name: tkwmailer-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tkwmailer
networks:
  tkwmailer:
    driver: bridge
